.c.obj:
  bcc -ms -c -w-pro $<

.asm.obj:
  tasm /ml $*

all: 1 3

1: l17-1.exe

3: l17-3.exe

# noehs.lib disables exception handling
# remove the reference if the lib is not available
l17-1.exe: l17-1.obj l17-2.obj
  bcc -ms l17-1.c l17-2.c noehs.lib

l17-3.exe: l17-3.obj l17-2.obj
  bcc -ms l17-3.obj l17-2.obj noehs.lib
