.c.obj:
  bcc -ms -c -w-pro $<

.asm.obj:
  tasm /ml $*

all: 1 3

1: l20-1.exe

3: l20-3.exe

# noehs.lib disables exception handling
# remove the reference if the lib is not available
l20-1.exe: l20-1.obj l20-2.obj
  bcc -ms l20-1.obj l20-2.obj noehs.lib

l20-3.exe: l20-3.obj l20-2.obj l20-4.obj
  bcc -ms l20-3.obj l20-2.obj l20-4.obj noehs.lib
