# noehs.lib disables exception handling
# remove the reference if the lib is not available
.c.obj:
  bcc -ms -c -w-pro $<

.asm.obj:
  tasm /ml $*

l15-2.exe: l15-2.obj l16-1.obj
  bcc -ms l16-1.obj l15-2.obj noehs.lib
