.c.obj:
  bcc -ms -c -w-pro $<

.asm.obj:
  tasm /ml $*

l36-1.exe: l36-1.obj l36-2.obj l36-3.obj l36-4.obj l35-1.obj l35-2.obj \
           l21-1.obj l22-4.obj l32-1.obj l32-6.obj l34-6.obj
  bcc -ms l36-1.obj l36-2.obj l36-3.obj l36-4.obj l35-1.obj l35-2.obj \
          l21-1.obj l22-4.obj l32-1.obj l32-6.obj l34-6.obj noehs.lib
